# Generated by Django 5.2.2 on 2025-06-23 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=255)),
                ('address', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField()),
                ('row_level', models.CharField(choices=[('ground', 'Ground'), ('first', 'First'), ('second', 'Second')], max_length=100)),
                ('seat_type', models.CharField(choices=[('silver', 'Silver'), ('gold', 'Gold'), ('recliner', 'Recliner')], max_length=100)),
                ('is_booked', models.BooleanField(default=False)),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theaters.theater')),
            ],
        ),
    ]
