# Generated by Django 5.2.2 on 2025-06-30 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0004_movie_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=255)),
                ('address', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='ShowTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_time', models.DateTimeField()),
                ('silver_seats', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gold_seats', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('platinum_seats', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('movie_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theaters.theater')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField()),
                ('row_label', models.CharField(choices=[('ground', 'Ground'), ('first', 'First'), ('second', 'Second')], max_length=100)),
                ('seat_type', models.CharField(choices=[('silver', 'Silver'), ('gold', 'Gold'), ('recliner', 'Recliner')], max_length=100)),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theaters.theater')),
            ],
        ),
    ]
