# Generated by Django 5.2.2 on 2025-06-17 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_opt_expiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='opt_expiry',
            new_name='otp_expiry',
        ),
    ]
