# Generated by Django 5.2.2 on 2025-06-30 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingSeat',
        ),
    ]
